
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author a
 */
public class show extends javax.swing.JFrame {
    
    
    
    
    
    
    TotalRun tR = new TotalRun();
    Bowling bln = new Bowling();
   
    scoreBoard sb = new scoreBoard();
    BowlingScore bs = new BowlingScore();
    ExtraRun ex = new ExtraRun();

    /**
     * Creates new form show
     * 
     */
    
    batsMan [] b = new batsMan[11];
    
    Bowler [] bL = new Bowler[11];
    
            
    
     
    
    
    
    
    JPanel panel =new JPanel(); 
    
    ButtonGroup button = new ButtonGroup();
    ButtonGroup bowlerButton = new ButtonGroup();
    ButtonGroup bx = new ButtonGroup();
    
    public show() {
        initComponents();
        
      
        
         b[0] = new batsMan();
         b[1] = new batsMan();
         b[2] = new batsMan();
         b[3] = new batsMan();
         b[4] = new batsMan();
         b[5] = new batsMan();
         b[6] = new batsMan();
         b[7] = new batsMan();
         b[8] = new batsMan();
         b[9] = new batsMan();
         b[10] = new batsMan();
         
         bL[0] = new Bowler();
     bL[1] = new Bowler();
     bL[2] = new Bowler();
     bL[3] = new Bowler();
     bL[4] = new Bowler();
     bL[5] = new Bowler();
     bL[6] = new Bowler();
     bL[7] = new Bowler();
     bL[8] = new Bowler();
     bL[9] = new Bowler();
     bL[10] = new Bowler();
     
     bx.add(batButton);
     bx.add(extraButton);
        
        
        button.add(batsman_1Button);
        button.add(batsman_2Button);
        button.add(batsman_3Button);
        button.add(batsman_4Button);
        button.add(batsman_5Button);
        button.add(batsman_6Button);
        button.add(batsman_7Button);
        button.add(batsman_8Button);
        button.add(batsman_9Button);
        button.add(batsman_10Button);
        button.add(batsman_11Button);
        
        bowlerButton.add(bowler_1Button);
        bowlerButton.add(bowler_2Button);
        bowlerButton.add(bowler_3Button);
        bowlerButton.add(bowler_4Button);
        bowlerButton.add(bowler_5Button);
        bowlerButton.add(bowler_6Button);
        bowlerButton.add(bowler_7Button);
        bowlerButton.add(bowler_8Button);
        bowlerButton.add(bowler_9Button);
        bowlerButton.add(bowler_10Button);
        bowlerButton.add(bowler_11Button);
       
        
       /* panel.add(batsman_1Button);
        panel.add(batsman_2Button);
        panel.add(batsman_3Button);
        panel.add(batsman_4Button);
        panel.add(batsman_5Button);
        panel.add(batsman_6Button);
        panel.add(batsman_7Button);
        panel.add(batsman_8Button);
        panel.add(batsman_9Button);
        panel.add(batsman_10Button);
        panel.add(batsman_11Button);
        panel.setVisible(true);
        jInternalFrame1.add(panel);*/
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        onerunButton = new javax.swing.JButton();
        tworunButton = new javax.swing.JButton();
        threerunButton = new javax.swing.JButton();
        fourrunButton = new javax.swing.JButton();
        fiverunButton = new javax.swing.JButton();
        sixrunButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        batsman_1Button = new javax.swing.JRadioButton();
        batsman_2Button = new javax.swing.JRadioButton();
        totalRunButton = new javax.swing.JButton();
        batsman_3Button = new javax.swing.JRadioButton();
        batsman_4Button = new javax.swing.JRadioButton();
        batsman_5Button = new javax.swing.JRadioButton();
        batsman_6Button = new javax.swing.JRadioButton();
        batsman_7Button = new javax.swing.JRadioButton();
        batsman_8Button = new javax.swing.JRadioButton();
        batsman_9Button = new javax.swing.JRadioButton();
        batsman_10Button = new javax.swing.JRadioButton();
        batsman_11Button = new javax.swing.JRadioButton();
        outButton = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jInternalFrame2 = new javax.swing.JInternalFrame();
        jLabel2 = new javax.swing.JLabel();
        oneballButton = new javax.swing.JButton();
        twoballButton = new javax.swing.JButton();
        threeballButton = new javax.swing.JButton();
        fourballButton = new javax.swing.JButton();
        fiveballButton = new javax.swing.JButton();
        sixballButton = new javax.swing.JButton();
        bowler_9Button = new javax.swing.JRadioButton();
        bowler_10Button = new javax.swing.JRadioButton();
        bowler_11Button = new javax.swing.JRadioButton();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        bowler_1Button = new javax.swing.JRadioButton();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        bowler_2Button = new javax.swing.JRadioButton();
        jLayeredPane3 = new javax.swing.JLayeredPane();
        bowler_3Button = new javax.swing.JRadioButton();
        jLayeredPane4 = new javax.swing.JLayeredPane();
        bowler_4Button = new javax.swing.JRadioButton();
        jLayeredPane5 = new javax.swing.JLayeredPane();
        bowler_6Button = new javax.swing.JRadioButton();
        bowler_7Button = new javax.swing.JRadioButton();
        bowler_8Button = new javax.swing.JRadioButton();
        bowler_5Button = new javax.swing.JRadioButton();
        extraButton = new javax.swing.JRadioButton();
        batButton = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jInternalFrame1.setVisible(true);

        onerunButton.setText("1");
        onerunButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onerunButtonActionPerformed(evt);
            }
        });

        tworunButton.setText("2");
        tworunButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tworunButtonActionPerformed(evt);
            }
        });

        threerunButton.setText("3");
        threerunButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                threerunButtonActionPerformed(evt);
            }
        });

        fourrunButton.setText("4");
        fourrunButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fourrunButtonActionPerformed(evt);
            }
        });

        fiverunButton.setText("5");
        fiverunButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fiverunButtonActionPerformed(evt);
            }
        });

        sixrunButton.setText("6");
        sixrunButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sixrunButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Enter Run");

        batsman_1Button.setText("Batsman_1");
        batsman_1Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batsman_1ButtonActionPerformed(evt);
            }
        });

        batsman_2Button.setText("Batsman_2");
        batsman_2Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batsman_2ButtonActionPerformed(evt);
            }
        });

        totalRunButton.setText("Total");
        totalRunButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalRunButtonActionPerformed(evt);
            }
        });

        batsman_3Button.setText("Batsman_3");
        batsman_3Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batsman_3ButtonActionPerformed(evt);
            }
        });

        batsman_4Button.setText("Batsman_4");
        batsman_4Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batsman_4ButtonActionPerformed(evt);
            }
        });

        batsman_5Button.setText("Batsman_5");
        batsman_5Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batsman_5ButtonActionPerformed(evt);
            }
        });

        batsman_6Button.setText("Batsman_6");
        batsman_6Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batsman_6ButtonActionPerformed(evt);
            }
        });

        batsman_7Button.setText("Batsman_7");
        batsman_7Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batsman_7ButtonActionPerformed(evt);
            }
        });

        batsman_8Button.setText("Batsman_8");
        batsman_8Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batsman_8ButtonActionPerformed(evt);
            }
        });

        batsman_9Button.setText("Batsman_9");
        batsman_9Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batsman_9ButtonActionPerformed(evt);
            }
        });

        batsman_10Button.setText("Batsman_10");
        batsman_10Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batsman_10ButtonActionPerformed(evt);
            }
        });

        batsman_11Button.setText("Batsman_11");
        batsman_11Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batsman_11ButtonActionPerformed(evt);
            }
        });

        outButton.setText("OUT");
        outButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outButtonActionPerformed(evt);
            }
        });

        jButton2.setText("Display");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame1Layout.createSequentialGroup()
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                .addComponent(fourrunButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(batsman_6Button)
                                    .addComponent(batsman_1Button)
                                    .addComponent(batsman_2Button)
                                    .addComponent(batsman_3Button)
                                    .addComponent(batsman_4Button)
                                    .addComponent(batsman_5Button)))
                            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(threerunButton)
                                    .addComponent(onerunButton)
                                    .addComponent(tworunButton))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jInternalFrame1Layout.createSequentialGroup()
                                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fiverunButton)
                                    .addComponent(sixrunButton))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(batsman_7Button))
                            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(batsman_11Button, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                .addComponent(outButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(batsman_8Button))
                            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                .addComponent(totalRunButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(batsman_9Button))
                            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                                .addComponent(batsman_10Button)))
                        .addGap(30, 30, 30))))
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(onerunButton))
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(batsman_1Button)
                        .addGap(31, 31, 31)
                        .addComponent(batsman_2Button)))
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(tworunButton))
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(batsman_3Button)))
                .addGap(1, 1, 1)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(threerunButton)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(batsman_4Button)))
                .addGap(26, 26, 26)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(batsman_5Button)
                    .addComponent(fourrunButton))
                .addGap(26, 26, 26)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fiverunButton)
                    .addComponent(batsman_6Button))
                .addGap(28, 28, 28)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sixrunButton)
                    .addComponent(batsman_7Button))
                .addGap(26, 26, 26)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(batsman_8Button)
                    .addComponent(outButton))
                .addGap(26, 26, 26)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(batsman_9Button)
                    .addComponent(totalRunButton))
                .addGap(25, 25, 25)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(batsman_10Button)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(batsman_11Button)
                .addContainerGap(79, Short.MAX_VALUE))
        );

        jInternalFrame2.setVisible(true);

        jLabel2.setText("Enter balls");

        oneballButton.setText("1");
        oneballButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oneballButtonActionPerformed(evt);
            }
        });

        twoballButton.setText("2");
        twoballButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twoballButtonActionPerformed(evt);
            }
        });

        threeballButton.setText("3");
        threeballButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                threeballButtonActionPerformed(evt);
            }
        });

        fourballButton.setText("4");
        fourballButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fourballButtonActionPerformed(evt);
            }
        });

        fiveballButton.setText("5");
        fiveballButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fiveballButtonActionPerformed(evt);
            }
        });

        sixballButton.setText("6");
        sixballButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sixballButtonActionPerformed(evt);
            }
        });

        bowler_9Button.setText("Bowler_9");
        bowler_9Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bowler_9ButtonActionPerformed(evt);
            }
        });

        bowler_10Button.setText("Bowler_10");
        bowler_10Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bowler_10ButtonActionPerformed(evt);
            }
        });

        bowler_11Button.setText("Bowler_11");
        bowler_11Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bowler_11ButtonActionPerformed(evt);
            }
        });

        bowler_1Button.setText("Bowler_1");
        bowler_1Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bowler_1ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bowler_1Button)
                .addContainerGap())
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bowler_1Button)
                .addContainerGap())
        );
        jLayeredPane1.setLayer(bowler_1Button, javax.swing.JLayeredPane.DEFAULT_LAYER);

        bowler_2Button.setText("Bowler_2");
        bowler_2Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bowler_2ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jLayeredPane2Layout = new javax.swing.GroupLayout(jLayeredPane2);
        jLayeredPane2.setLayout(jLayeredPane2Layout);
        jLayeredPane2Layout.setHorizontalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bowler_2Button)
                .addContainerGap())
        );
        jLayeredPane2Layout.setVerticalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bowler_2Button)
                .addContainerGap())
        );
        jLayeredPane2.setLayer(bowler_2Button, javax.swing.JLayeredPane.DEFAULT_LAYER);

        bowler_3Button.setText("Bowler_3");
        bowler_3Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bowler_3ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jLayeredPane3Layout = new javax.swing.GroupLayout(jLayeredPane3);
        jLayeredPane3.setLayout(jLayeredPane3Layout);
        jLayeredPane3Layout.setHorizontalGroup(
            jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bowler_3Button)
                .addContainerGap())
        );
        jLayeredPane3Layout.setVerticalGroup(
            jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bowler_3Button)
                .addContainerGap())
        );
        jLayeredPane3.setLayer(bowler_3Button, javax.swing.JLayeredPane.DEFAULT_LAYER);

        bowler_4Button.setText("Bowler_4");
        bowler_4Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bowler_4ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jLayeredPane4Layout = new javax.swing.GroupLayout(jLayeredPane4);
        jLayeredPane4.setLayout(jLayeredPane4Layout);
        jLayeredPane4Layout.setHorizontalGroup(
            jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bowler_4Button)
                .addContainerGap())
        );
        jLayeredPane4Layout.setVerticalGroup(
            jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bowler_4Button)
                .addContainerGap())
        );
        jLayeredPane4.setLayer(bowler_4Button, javax.swing.JLayeredPane.DEFAULT_LAYER);

        bowler_6Button.setText("Bowler_6");
        bowler_6Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bowler_6ButtonActionPerformed(evt);
            }
        });

        bowler_7Button.setText("Bowler_7");
        bowler_7Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bowler_7ButtonActionPerformed(evt);
            }
        });

        bowler_8Button.setText("Bowler_8");
        bowler_8Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bowler_8ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jLayeredPane5Layout = new javax.swing.GroupLayout(jLayeredPane5);
        jLayeredPane5.setLayout(jLayeredPane5Layout);
        jLayeredPane5Layout.setHorizontalGroup(
            jLayeredPane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane5Layout.createSequentialGroup()
                        .addComponent(bowler_6Button)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane5Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jLayeredPane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bowler_7Button, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(bowler_8Button, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        jLayeredPane5Layout.setVerticalGroup(
            jLayeredPane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bowler_6Button)
                .addGap(18, 18, 18)
                .addComponent(bowler_7Button)
                .addGap(18, 18, 18)
                .addComponent(bowler_8Button)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLayeredPane5.setLayer(bowler_6Button, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane5.setLayer(bowler_7Button, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane5.setLayer(bowler_8Button, javax.swing.JLayeredPane.DEFAULT_LAYER);

        bowler_5Button.setText("Bowler_5");
        bowler_5Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bowler_5ButtonActionPerformed(evt);
            }
        });

        extraButton.setText("EXTRA");
        extraButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                extraButtonActionPerformed(evt);
            }
        });

        batButton.setText("BAT");
        batButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jInternalFrame2Layout = new javax.swing.GroupLayout(jInternalFrame2.getContentPane());
        jInternalFrame2.getContentPane().setLayout(jInternalFrame2Layout);
        jInternalFrame2Layout.setHorizontalGroup(
            jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jInternalFrame2Layout.createSequentialGroup()
                        .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jInternalFrame2Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(oneballButton)
                                    .addComponent(twoballButton)
                                    .addComponent(threeballButton)
                                    .addComponent(fiveballButton)
                                    .addComponent(sixballButton)
                                    .addComponent(fourballButton)
                                    .addComponent(extraButton)))
                            .addComponent(batButton))
                        .addGap(25, 25, 25)
                        .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLayeredPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLayeredPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLayeredPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bowler_5Button)
                            .addComponent(bowler_9Button, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bowler_10Button, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bowler_11Button, javax.swing.GroupLayout.Alignment.LEADING))))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jInternalFrame2Layout.setVerticalGroup(
            jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame2Layout.createSequentialGroup()
                .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame2Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addComponent(oneballButton)
                        .addGap(18, 18, 18)
                        .addComponent(twoballButton))
                    .addGroup(jInternalFrame2Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame2Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(threeballButton))
                    .addGroup(jInternalFrame2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLayeredPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(3, 3, 3)
                .addComponent(jLayeredPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame2Layout.createSequentialGroup()
                        .addComponent(fourballButton)
                        .addGap(30, 30, 30))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame2Layout.createSequentialGroup()
                        .addComponent(bowler_5Button)
                        .addGap(18, 18, 18)))
                .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame2Layout.createSequentialGroup()
                        .addComponent(jLayeredPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(bowler_9Button)
                        .addGap(18, 18, 18)
                        .addComponent(bowler_10Button))
                    .addGroup(jInternalFrame2Layout.createSequentialGroup()
                        .addComponent(fiveballButton)
                        .addGap(28, 28, 28)
                        .addComponent(sixballButton)
                        .addGap(40, 40, 40)
                        .addComponent(extraButton)
                        .addGap(35, 35, 35)
                        .addComponent(batButton)))
                .addGap(18, 18, 18)
                .addComponent(bowler_11Button)
                .addGap(0, 75, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 106, Short.MAX_VALUE)
                .addComponent(jInternalFrame2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jInternalFrame2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(904, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void oneballButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oneballButtonActionPerformed
        // TODO add your handling code here:
        bln.setBalls(1);
        
       for(int i=0;i<bL.length;i++){
       
           if(bL[i].status==1){
            bL[i].setBalls(1);
            
        }
       }
        
    }//GEN-LAST:event_oneballButtonActionPerformed

    private void bowler_1ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bowler_1ButtonActionPerformed
        // TODO add your handling code here:
        if(bL[0].bName == null){
        String bowler = JOptionPane.showInputDialog("Enter bowler Name");
           bL[0].setName(bowler);
           bowler_1Button.setText(bowler);
           bs.table_2.setValueAt(bowler, 0, 0);
           
        }
        
        bL[0].setStatus(1);
        bL[1].setStatus(0);
        bL[2].setStatus(0);
        bL[3].setStatus(0);
        bL[4].setStatus(0);
        bL[5].setStatus(0);
        bL[6].setStatus(0);
        bL[7].setStatus(0);
        bL[8].setStatus(0);
        bL[9].setStatus(0);
        bL[10].setStatus(0);
      
    }//GEN-LAST:event_bowler_1ButtonActionPerformed

    private void twoballButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twoballButtonActionPerformed
        // TODO add your handling code here:
        bln.setBalls(2);
        
        for(int i=0;i<bL.length;i++){
       
           if(bL[i].status==1){
            bL[i].setBalls(1);
            
        }
       }
            
        
    }//GEN-LAST:event_twoballButtonActionPerformed

    private void threeballButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_threeballButtonActionPerformed
        // TODO add your handling code here:
        bln.setBalls(3);
        
        for(int i=0;i<bL.length;i++){
       
           if(bL[i].status==1){
            bL[i].setBalls(1);
            
        }
       }
    }//GEN-LAST:event_threeballButtonActionPerformed

    private void fourballButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fourballButtonActionPerformed
        // TODO add your handling code here:
        bln.setBalls(4);
        
        for(int i=0;i<bL.length;i++){
       
           if(bL[i].status==1){
            bL[i].setBalls(1);
            
        }
       }
    }//GEN-LAST:event_fourballButtonActionPerformed

    private void fiveballButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fiveballButtonActionPerformed
        // TODO add your handling code here:
        bln.setBalls(5);
        
        for(int i=0;i<bL.length;i++){
       
           if(bL[i].status==1){
            bL[i].setBalls(1);
            
        }
       }
    }//GEN-LAST:event_fiveballButtonActionPerformed

    private void sixballButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sixballButtonActionPerformed
        // TODO add your handling code here:
        bln.setOvers(6);
        bln.setBalls(0);
        for(int i=0;i<bL.length;i++){
       
           if(bL[i].status==1){
            bL[i].setOvers(6);
            bL[i].setBalls(1);
            
        }
       }
    }//GEN-LAST:event_sixballButtonActionPerformed

    private void bowler_2ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bowler_2ButtonActionPerformed
        // TODO add your handling code here:
         if(bL[1].bName == null){
        String bowler = JOptionPane.showInputDialog("Enter bowler Name");
           bL[1].setName(bowler);
           bowler_2Button.setText(bowler);
           bs.table_2.setValueAt(bowler, 1, 0);
        }
        
        bL[0].setStatus(0);
        bL[1].setStatus(1);
        bL[2].setStatus(0);
        bL[3].setStatus(0);
        bL[4].setStatus(0);
        bL[5].setStatus(0);
        bL[6].setStatus(0);
        bL[7].setStatus(0);
        bL[8].setStatus(0);
        bL[9].setStatus(0);
        bL[10].setStatus(0);
    }//GEN-LAST:event_bowler_2ButtonActionPerformed

    private void bowler_3ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bowler_3ButtonActionPerformed
        // TODO add your handling code here:
        if(bL[2].bName == null){
        String bowler = JOptionPane.showInputDialog("Enter bowler Name");
           bL[2].setName(bowler);
           bowler_3Button.setText(bowler);
           bs.table_2.setValueAt(bowler, 2, 0);
        }
        
        bL[0].setStatus(0);
        bL[1].setStatus(0);
        bL[2].setStatus(1);
        bL[3].setStatus(0);
        bL[4].setStatus(0);
        bL[5].setStatus(0);
        bL[6].setStatus(0);
        bL[7].setStatus(0);
        bL[8].setStatus(0);
        bL[9].setStatus(0);
        bL[10].setStatus(0);
    }//GEN-LAST:event_bowler_3ButtonActionPerformed

    private void bowler_4ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bowler_4ButtonActionPerformed
        // TODO add your handling code here:
        if(bL[3].bName == null){
        String bowler = JOptionPane.showInputDialog("Enter bowler Name");
           bL[3].setName(bowler);
           bowler_4Button.setText(bowler);
           bs.table_2.setValueAt(bowler, 3, 0);
        }
        
        bL[0].setStatus(0);
        bL[1].setStatus(0);
        bL[2].setStatus(0);
        bL[3].setStatus(1);
        bL[4].setStatus(0);
        bL[5].setStatus(0);
        bL[6].setStatus(0);
        bL[7].setStatus(0);
        bL[8].setStatus(0);
        bL[9].setStatus(0);
        bL[10].setStatus(0);
    }//GEN-LAST:event_bowler_4ButtonActionPerformed

    private void bowler_5ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bowler_5ButtonActionPerformed
        // TODO add your handling code here:
        if(bL[4].bName == null){
        String bowler = JOptionPane.showInputDialog("Enter bowler Name");
           bL[4].setName(bowler);
           bowler_5Button.setText(bowler);
           bs.table_2.setValueAt(bowler, 4, 0);
        }
        
        bL[0].setStatus(0);
        bL[1].setStatus(0);
        bL[2].setStatus(0);
        bL[3].setStatus(0);
        bL[4].setStatus(1);
        bL[5].setStatus(0);
        bL[6].setStatus(0);
        bL[7].setStatus(0);
        bL[8].setStatus(0);
        bL[9].setStatus(0);
        bL[10].setStatus(0);
    }//GEN-LAST:event_bowler_5ButtonActionPerformed

    private void bowler_6ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bowler_6ButtonActionPerformed
        // TODO add your handling code here:
        if(bL[5].bName == null){
        String bowler = JOptionPane.showInputDialog("Enter bowler Name");
           bL[5].setName(bowler);
           bowler_6Button.setText(bowler);
           bs.table_2.setValueAt(bowler, 5, 0);
        }
        
        bL[0].setStatus(0);
        bL[1].setStatus(0);
        bL[2].setStatus(0);
        bL[3].setStatus(0);
        bL[4].setStatus(0);
        bL[5].setStatus(1);
        bL[6].setStatus(0);
        bL[7].setStatus(0);
        bL[8].setStatus(0);
        bL[9].setStatus(0);
        bL[10].setStatus(0);
    }//GEN-LAST:event_bowler_6ButtonActionPerformed

    private void bowler_7ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bowler_7ButtonActionPerformed
        // TODO add your handling code here:
        if(bL[6].bName == null){
        String bowler = JOptionPane.showInputDialog("Enter bowler Name");
           bL[6].setName(bowler);
           bowler_7Button.setText(bowler);
           bs.table_2.setValueAt(bowler, 6, 0);
        }
        
        bL[0].setStatus(0);
        bL[1].setStatus(0);
        bL[2].setStatus(0);
        bL[3].setStatus(0);
        bL[4].setStatus(0);
        bL[5].setStatus(0);
        bL[6].setStatus(1);
        bL[7].setStatus(0);
        bL[8].setStatus(0);
        bL[9].setStatus(0);
        bL[10].setStatus(0);
    }//GEN-LAST:event_bowler_7ButtonActionPerformed

    private void bowler_8ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bowler_8ButtonActionPerformed
        // TODO add your handling code here:
        if(bL[7].bName == null){
        String bowler = JOptionPane.showInputDialog("Enter bowler Name");
           bL[7].setName(bowler);
           bowler_8Button.setText(bowler);
           bs.table_2.setValueAt(bowler, 7, 0);
        }
        
        bL[0].setStatus(0);
        bL[1].setStatus(0);
        bL[2].setStatus(0);
        bL[3].setStatus(0);
        bL[4].setStatus(0);
        bL[5].setStatus(0);
        bL[6].setStatus(0);
        bL[7].setStatus(1);
        bL[8].setStatus(0);
        bL[9].setStatus(0);
        bL[10].setStatus(0);
    }//GEN-LAST:event_bowler_8ButtonActionPerformed

    private void bowler_9ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bowler_9ButtonActionPerformed
        // TODO add your handling code here:
        if(bL[8].bName == null){
        String bowler = JOptionPane.showInputDialog("Enter bowler Name");
           bL[8].setName(bowler);
           bowler_9Button.setText(bowler);
           bs.table_2.setValueAt(bowler, 8, 0);
        }
        
        bL[0].setStatus(0);
        bL[1].setStatus(0);
        bL[2].setStatus(0);
        bL[3].setStatus(0);
        bL[4].setStatus(0);
        bL[5].setStatus(0);
        bL[6].setStatus(0);
        bL[7].setStatus(0);
        bL[8].setStatus(1);
        bL[9].setStatus(0);
        bL[10].setStatus(0);
    }//GEN-LAST:event_bowler_9ButtonActionPerformed

    private void bowler_10ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bowler_10ButtonActionPerformed
        // TODO add your handling code here:
        if(bL[9].bName == null){
        String bowler = JOptionPane.showInputDialog("Enter bowler Name");
           bL[9].setName(bowler);
           bowler_10Button.setText(bowler);
           bs.table_2.setValueAt(bowler, 9, 0);
        }
        
        bL[0].setStatus(0);
        bL[1].setStatus(0);
        bL[2].setStatus(0);
        bL[3].setStatus(0);
        bL[4].setStatus(0);
        bL[5].setStatus(0);
        bL[6].setStatus(0);
        bL[7].setStatus(0);
        bL[8].setStatus(0);
        bL[9].setStatus(1);
        bL[10].setStatus(0);
    }//GEN-LAST:event_bowler_10ButtonActionPerformed

    private void bowler_11ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bowler_11ButtonActionPerformed
        // TODO add your handling code here:
        if(bL[10].bName == null){
        String bowler = JOptionPane.showInputDialog("Enter bowler Name");
           bL[10].setName(bowler);
           bowler_11Button.setText(bowler);
           bs.table_2.setValueAt(bowler, 10, 0);
        }
        
        bL[0].setStatus(0);
        bL[1].setStatus(0);
        bL[2].setStatus(0);
        bL[3].setStatus(0);
        bL[4].setStatus(0);
        bL[5].setStatus(0);
        bL[6].setStatus(0);
        bL[7].setStatus(0);
        bL[8].setStatus(0);
        bL[9].setStatus(0);
        bL[10].setStatus(1);
    }//GEN-LAST:event_bowler_11ButtonActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        

      for(int i=0;i<b.length;i++){
      
          sb.table.setValueAt(b[i].getRun(), i, 3);
          
          sb.table.setValueAt(b[i].getBallsPlayed(), i, 2);
          
          if(b[i].getOut()==true){
          
             sb.table.setValueAt("OUT", i, 1); 
          }
          
          else if(b[i].getOut()==false && b[i].getBallsPlayed()==0){
          
              sb.table.setValueAt("Did Not Bat", i, 1); 
          }
          
          else{
          
              sb.table.setValueAt("NOT OUT", i, 1); 
          }
      }
      
      sb.table.setValueAt(ex.getExtra(), 11, 3);
      sb.table.setValueAt(tR.getRun(), 12, 3);
      
      for(int i=0;i<bL.length;i++){
      
          bs.table_2.setValueAt(bL[i].getOvers(), i, 1);
          
          bs.table_2.setValueAt(bL[i].getWickets(), i, 2);
          
          bs.table_2.setValueAt(bL[i].getRun(), i, 3);
          
          
       
          bs.table_2.setValueAt(bL[i].getEconomy(), i, 4);
      }
      
      
      
      bs.table_2.setValueAt(ex.getExtra(), 11, 3);
      
      
      
        sb.frame.setVisible(true);
        
        bs.frame_2.setVisible(true);
      
    
        
       
       
    }//GEN-LAST:event_jButton2ActionPerformed

    private void outButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outButtonActionPerformed
        // TODO add your handling code here:
        for(int i=0;i<b.length;i++){

            if(b[i].status==1){

                b[i].setOut(true);
                System.out.println(b[i].getName()+" is out");
            }
        }

        for(int i=0;i<b.length;i++){

            if(bL[i].status==1){

                bL[i].setWickets();
                System.out.println(bL[i].getName()+" has  got the wicket");
            }
        }
    }//GEN-LAST:event_outButtonActionPerformed

    private void batsman_11ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batsman_11ButtonActionPerformed
        // TODO add your handling code here:
        if(b[10].name == null){

            String batsman= JOptionPane.showInputDialog("Enter Name");
            b[10].setName(batsman);
            batsman_11Button.setText(batsman);
            sb.table.setValueAt(batsman, 10, 0);

        }

        if(b[10].out==true){

            batsman_11Button.setEnabled(false);
            b[10].setStatus(0);
        }

        else
        b[10].setStatus(1);

        b[0].setStatus(0);
        b[1].setStatus(0);
        b[2].setStatus(0);
        b[3].setStatus(0);
        b[4].setStatus(0);
        b[5].setStatus(0);
        b[6].setStatus(0);
        b[7].setStatus(0);
        b[8].setStatus(0);
        b[9].setStatus(0);
        // b[10].setStatus(1);
    }//GEN-LAST:event_batsman_11ButtonActionPerformed

    private void batsman_10ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batsman_10ButtonActionPerformed
        // TODO add your handling code here:
        if(b[9].name == null){

            String batsman= JOptionPane.showInputDialog("Enter Name");
            b[9].setName(batsman);
            batsman_10Button.setText(batsman);
            sb.table.setValueAt(batsman, 9, 0);

        }

        if(b[9].out==true){

            batsman_10Button.setEnabled(false);
            b[9].setStatus(0);
        }

        else
        b[9].setStatus(1);

        b[0].setStatus(0);
        b[1].setStatus(0);
        b[2].setStatus(0);
        b[3].setStatus(0);
        b[4].setStatus(0);
        b[5].setStatus(0);
        b[6].setStatus(0);
        b[7].setStatus(0);
        b[8].setStatus(0);
        //b[9].setStatus(1);
        b[10].setStatus(0);
    }//GEN-LAST:event_batsman_10ButtonActionPerformed

    private void batsman_9ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batsman_9ButtonActionPerformed
        // TODO add your handling code here:
        if(b[8].name == null){

            String batsman= JOptionPane.showInputDialog("Enter Name");
            b[8].setName(batsman);
            batsman_9Button.setText(batsman);
            sb.table.setValueAt(batsman, 8, 0);

        }

        if(b[8].out==true){

            batsman_9Button.setEnabled(false);
            b[8].setStatus(0);
        }

        else
        b[8].setStatus(1);

        b[0].setStatus(0);
        b[1].setStatus(0);
        b[2].setStatus(0);
        b[3].setStatus(0);
        b[4].setStatus(0);
        b[5].setStatus(0);
        b[6].setStatus(0);
        b[7].setStatus(0);
        // b[8].setStatus(1);
        b[9].setStatus(0);
        b[10].setStatus(0);
    }//GEN-LAST:event_batsman_9ButtonActionPerformed

    private void batsman_8ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batsman_8ButtonActionPerformed
        // TODO add your handling code here:
        if(b[7].name == null){

            String batsman= JOptionPane.showInputDialog("Enter Name");
            b[7].setName(batsman);
            batsman_8Button.setText(batsman);
            sb.table.setValueAt(batsman, 7, 0);

        }

        if(b[7].out==true){

            batsman_8Button.setEnabled(false);
            b[7].setStatus(0);
        }

        else
        b[7].setStatus(1);

        b[0].setStatus(0);
        b[1].setStatus(0);
        b[2].setStatus(0);
        b[3].setStatus(0);
        b[4].setStatus(0);
        b[5].setStatus(0);
        b[6].setStatus(0);
        // b[7].setStatus(1);
        b[8].setStatus(0);
        b[9].setStatus(0);
        b[10].setStatus(0);
    }//GEN-LAST:event_batsman_8ButtonActionPerformed

    private void batsman_7ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batsman_7ButtonActionPerformed
        // TODO add your handling code here:
        if(b[6].name == null){

            String batsman= JOptionPane.showInputDialog("Enter Name");
            b[0].setName(batsman);
            batsman_7Button.setText(batsman);
            sb.table.setValueAt(batsman, 6, 0);

        }

        if(b[6].out==true){

            batsman_7Button.setEnabled(false);
            b[6].setStatus(0);
        }

        else
        b[6].setStatus(1);

        b[0].setStatus(0);
        b[1].setStatus(0);
        b[2].setStatus(0);
        b[3].setStatus(0);
        b[4].setStatus(0);
        b[5].setStatus(0);
        //b[6].setStatus(1);
        b[7].setStatus(0);
        b[8].setStatus(0);
        b[9].setStatus(0);
        b[10].setStatus(0);
    }//GEN-LAST:event_batsman_7ButtonActionPerformed

    private void batsman_6ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batsman_6ButtonActionPerformed
        // TODO add your handling code here:
        if(b[5].name == null){

            String batsman= JOptionPane.showInputDialog("Enter Name");
            b[5].setName(batsman);
            batsman_6Button.setText(batsman);
            sb.table.setValueAt(batsman, 5, 0);

        }

        if(b[5].out==true){

            batsman_6Button.setEnabled(false);
            b[5].setStatus(0);
        }

        else
        b[5].setStatus(1);

        b[0].setStatus(0);
        b[1].setStatus(0);
        b[2].setStatus(0);
        b[3].setStatus(0);
        b[4].setStatus(0);
        //b[5].setStatus(1);
        b[6].setStatus(0);
        b[7].setStatus(0);
        b[8].setStatus(0);
        b[9].setStatus(0);
        b[10].setStatus(0);
    }//GEN-LAST:event_batsman_6ButtonActionPerformed

    private void batsman_5ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batsman_5ButtonActionPerformed
        // TODO add your handling code here:
        if(b[4].name == null){

            String batsman= JOptionPane.showInputDialog("Enter Name");
            b[4].setName(batsman);
            batsman_5Button.setText(batsman);
            sb.table.setValueAt(batsman, 4, 0);

        }

        if(b[4].out==true){

            batsman_5Button.setEnabled(false);
            b[4].setStatus(0);
        }

        else
        b[4].setStatus(1);

        b[0].setStatus(0);
        b[1].setStatus(0);
        b[2].setStatus(0);
        b[3].setStatus(0);
        //b[4].setStatus(1);
        b[5].setStatus(0);
        b[6].setStatus(0);
        b[7].setStatus(0);
        b[8].setStatus(0);
        b[9].setStatus(0);
        b[10].setStatus(0);
    }//GEN-LAST:event_batsman_5ButtonActionPerformed

    private void batsman_4ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batsman_4ButtonActionPerformed
        // TODO add your handling code here:
        if(b[3].name == null){

            String batsman= JOptionPane.showInputDialog("Enter Name");
            b[3].setName(batsman);
            batsman_4Button.setText(batsman);
            sb.table.setValueAt(batsman, 3, 0);

        }

        if(b[3].out==true){

            batsman_4Button.setEnabled(false);
            b[3].setStatus(0);
        }

        else
        b[3].setStatus(1);

        b[0].setStatus(0);
        b[1].setStatus(0);
        b[2].setStatus(0);
        //b[3].setStatus(1);
        b[4].setStatus(0);
        b[5].setStatus(0);
        b[6].setStatus(0);
        b[7].setStatus(0);
        b[8].setStatus(0);
        b[9].setStatus(0);
        b[10].setStatus(0);
    }//GEN-LAST:event_batsman_4ButtonActionPerformed

    private void batsman_3ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batsman_3ButtonActionPerformed
        // TODO add your handling code here:
        if(b[2].name == null){

            String batsman= JOptionPane.showInputDialog("Enter Name");
            b[2].setName(batsman);
            batsman_3Button.setText(batsman);
            sb.table.setValueAt(batsman, 2, 0);

        }

        if(b[2].out==true){

            batsman_3Button.setEnabled(false);
            b[2].setStatus(0);
        }

        else
        b[2].setStatus(1);

        b[0].setStatus(0);
        b[1].setStatus(0);
        // b[2].setStatus(1);
        b[3].setStatus(0);
        b[4].setStatus(0);
        b[5].setStatus(0);
        b[6].setStatus(0);
        b[7].setStatus(0);
        b[8].setStatus(0);
        b[9].setStatus(0);
        b[10].setStatus(0);
    }//GEN-LAST:event_batsman_3ButtonActionPerformed

    private void totalRunButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalRunButtonActionPerformed
        // TODO add your handling code here:
        System.out.println(tR.getRun()+" "+"is total ");

        for(int i=0;i<b.length;i++){

            System.out.println(b[i].getRun()+" is by "+b[i].getName());
        }

        for(int i=0;i<bL.length;i++){

            System.out.println(bL[i].getOvers()+" is by "+bL[i].getName());
        }

        System.out.println(bln.getOvers()+" "+"is total over ");

    }//GEN-LAST:event_totalRunButtonActionPerformed

    private void batsman_2ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batsman_2ButtonActionPerformed
        // TODO add your handling code here:
        if(b[1].name == null){

            String batsman= JOptionPane.showInputDialog("Enter Name");
            b[1].setName(batsman);
            batsman_2Button.setText(batsman);
            sb.table.setValueAt(batsman, 1, 0);

        }

        if(b[1].out==true){

            batsman_2Button.setEnabled(false);
            b[1].setStatus(0);
        }

        else
        b[1].setStatus(1);

        b[0].setStatus(0);
        //b[1].setStatus(1);
        b[2].setStatus(0);
        b[3].setStatus(0);
        b[4].setStatus(0);
        b[5].setStatus(0);
        b[6].setStatus(0);
        b[7].setStatus(0);
        b[8].setStatus(0);
        b[9].setStatus(0);
        b[10].setStatus(0);

    }//GEN-LAST:event_batsman_2ButtonActionPerformed

    private void batsman_1ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batsman_1ButtonActionPerformed
        // TODO add your handling code here:
        
        

        if(b[0].name == null){

            String batsman= JOptionPane.showInputDialog("Enter Name");
            b[0].setName(batsman);
            batsman_1Button.setText(batsman);
            sb.table.setValueAt(batsman, 0, 0);

        }

        if(b[0].out==true){

            batsman_1Button.setEnabled(false);
            b[0].setStatus(0);
        }

        else
        b[0].setStatus(1);

        b[1].setStatus(0);
        b[2].setStatus(0);
        b[3].setStatus(0);
        b[4].setStatus(0);
        b[5].setStatus(0);
        b[6].setStatus(0);
        b[7].setStatus(0);
        b[8].setStatus(0);
        b[9].setStatus(0);
        b[10].setStatus(0);

    }//GEN-LAST:event_batsman_1ButtonActionPerformed

    private void sixrunButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sixrunButtonActionPerformed
        // TODO add your handling code here:
        
        tR.setRun(6);
        if(ex.getIsExtra()==1){
        
            ex.setExtra(6);
        }
        
        
        

        for(int i=0;i<b.length;i++){

            if(b[i].status==1){
                b[i].setRun(6);
                b[i].setBallsPlayed();

            }
        }

        for(int i=0;i<bL.length;i++){

            if(bL[i].status==1){
                bL[i].setRun(6);

            }
        }

    }//GEN-LAST:event_sixrunButtonActionPerformed

    private void fiverunButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fiverunButtonActionPerformed
        // TODO add your handling code here:
        
        tR.setRun(5);
        
        if(ex.getIsExtra()==1){
        
            ex.setExtra(5);
        }
        
        

        for(int i=0;i<b.length;i++){

            if(b[i].status==1){
                b[i].setRun(5);
                b[i].setBallsPlayed();

            }
        }

        for(int i=0;i<bL.length;i++){

            if(bL[i].status==1){
                bL[i].setRun(5);

            }
        }

    }//GEN-LAST:event_fiverunButtonActionPerformed

    private void fourrunButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fourrunButtonActionPerformed
        // TODO add your handling code here:
        
        tR.setRun(4);
        if(ex.getIsExtra()==1){
        
            ex.setExtra(4);
        }
        
        
        

        for(int i=0;i<b.length;i++){

            if(b[i].status==1){
                b[i].setRun(4);
                b[i].setBallsPlayed();

            }
        }

        for(int i=0;i<bL.length;i++){

            if(bL[i].status==1){
                bL[i].setRun(4);

            }
        }

    }//GEN-LAST:event_fourrunButtonActionPerformed

    private void threerunButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_threerunButtonActionPerformed
        // TODO add your handling code here:
        
        tR.setRun(3);
        if(ex.getIsExtra()==1){
        
            ex.setExtra(3);
        }
        
        
        

        for(int i=0;i<b.length;i++){

            if(b[i].status==1){
                b[i].setRun(3);
                b[i].setBallsPlayed();

            }
        }

        for(int i=0;i<bL.length;i++){

            if(bL[i].status==1){
                bL[i].setRun(3);

            }
        }

    }//GEN-LAST:event_threerunButtonActionPerformed

    private void tworunButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tworunButtonActionPerformed
        // TODO add your handling code here:
        
        tR.setRun(2);
        if(ex.getIsExtra()==1){
        
            ex.setExtra(2);
        }

        
        

        for(int i=0;i<b.length;i++){

            if(b[i].status==1){
                b[i].setRun(2);
                b[i].setBallsPlayed();

            }
        }

        for(int i=0;i<bL.length;i++){

            if(bL[i].status==1){
                bL[i].setRun(2);

            }
        }

    }//GEN-LAST:event_tworunButtonActionPerformed

    private void onerunButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onerunButtonActionPerformed
        // TODO add your handling code here:
        
        tR.setRun(1);
        
        if(ex.getIsExtra()==1){
        
            ex.setExtra(1);
        }
        

        
        else{        
            for(int i=0;i<b.length;i++){

            if(b[i].status==1){
                b[i].setRun(1);
                b[i].setBallsPlayed();

            }
        }
     }

        for(int i=0;i<bL.length;i++){

            if(bL[i].status==1){
                bL[i].setRun(1);

            }
        }

    }//GEN-LAST:event_onerunButtonActionPerformed

    private void extraButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_extraButtonActionPerformed
        // TODO add your handling code here:
        
        ex.setIsExtra(1);
    }//GEN-LAST:event_extraButtonActionPerformed

    private void batButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batButtonActionPerformed
        // TODO add your handling code here:
        ex.setIsExtra(0);
    }//GEN-LAST:event_batButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(show.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(show.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(show.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(show.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new show().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton batButton;
    private javax.swing.JRadioButton batsman_10Button;
    private javax.swing.JRadioButton batsman_11Button;
    private javax.swing.JRadioButton batsman_1Button;
    private javax.swing.JRadioButton batsman_2Button;
    private javax.swing.JRadioButton batsman_3Button;
    private javax.swing.JRadioButton batsman_4Button;
    private javax.swing.JRadioButton batsman_5Button;
    private javax.swing.JRadioButton batsman_6Button;
    private javax.swing.JRadioButton batsman_7Button;
    private javax.swing.JRadioButton batsman_8Button;
    private javax.swing.JRadioButton batsman_9Button;
    private javax.swing.JRadioButton bowler_10Button;
    private javax.swing.JRadioButton bowler_11Button;
    private javax.swing.JRadioButton bowler_1Button;
    private javax.swing.JRadioButton bowler_2Button;
    private javax.swing.JRadioButton bowler_3Button;
    private javax.swing.JRadioButton bowler_4Button;
    private javax.swing.JRadioButton bowler_5Button;
    private javax.swing.JRadioButton bowler_6Button;
    private javax.swing.JRadioButton bowler_7Button;
    private javax.swing.JRadioButton bowler_8Button;
    private javax.swing.JRadioButton bowler_9Button;
    private javax.swing.JRadioButton extraButton;
    private javax.swing.JButton fiveballButton;
    private javax.swing.JButton fiverunButton;
    private javax.swing.JButton fourballButton;
    private javax.swing.JButton fourrunButton;
    private javax.swing.JButton jButton2;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JInternalFrame jInternalFrame2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JLayeredPane jLayeredPane3;
    private javax.swing.JLayeredPane jLayeredPane4;
    private javax.swing.JLayeredPane jLayeredPane5;
    private javax.swing.JButton oneballButton;
    private javax.swing.JButton onerunButton;
    private javax.swing.JButton outButton;
    private javax.swing.JButton sixballButton;
    private javax.swing.JButton sixrunButton;
    private javax.swing.JButton threeballButton;
    private javax.swing.JButton threerunButton;
    private javax.swing.JButton totalRunButton;
    private javax.swing.JButton twoballButton;
    private javax.swing.JButton tworunButton;
    // End of variables declaration//GEN-END:variables
}
